apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: accounts-api-route
  namespace: accounts-api
spec:
  parentRefs:
    - name: primary-gateway
      namespace: gateway
      sectionName: https-httptoolkit-tech
    - name: secondary-gateway
      namespace: gateway
      sectionName: https-httptoolkit-tech
  hostnames:
    - "accounts-api.httptoolkit.tech"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: accounts-api
          port: 4000